# Generated by Django 4.1.4 on 2022-12-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product", models.CharField(max_length=30)),
                ("description", models.TextField()),
                ("img", models.ImageField(null=True, upload_to="")),
                ("price", models.PositiveIntegerField()),
            ],
        ),
    ]
